### ISSUE TITLE
Editing a message reverts the message to the first edited version (Only in editing, only through right clicking)

### ISSUE THREAD

**Issue by Aida-Enna** [Syncxv/vc-message-logger-enhanced#41]
It sounds weird to explain so let me do it this way:
1) Send a message
2) Edit the message (using right click -> edit message) and have it be logged
3) Edit the message again (using right click -> edit message, may need to do it more than once) and the text once you hit edit will revert to a previous version (specifically the first saved edit?) but only on the edit mode. If you make no changes, it will show the current version of the message, but editing it will always show a specific older one.

Video explanation (I am clicking "Edit Message" in the right click menu each time I go to the top of it):
![Video explanation](https://github.com/Syncxv/vc-message-logger-enhanced/assets/5483362/e0f04d6a-f006-41bf-9627-e785580fcbb0)

Hitting up on the keyboard works as expected, it is specifically right click -> edit message where it does not work. When I disable Message Logger Enhanced, it works as expected.

**Comment by Syncxv** [comment]
i guess you want something like this?

this bug happened because i monkey patched the getMessage function and called that which returns the old logged message and not the new one. fixed here [080c28c](https://github.com/Syncxv/vc-message-logger-enhanced/commit/080c28c740ad0300b758a782f2cda9d758a78e88)

update and see if its fixed

![](https://i.imgur.com/sbVrRJp.gif)
