### ISSUE TITLE
Vesktop white screen

### ISSUE THREAD

**Issue by PinguLinux** [Syncxv/vc-message-logger-enhanced#5]
Since discord updated the classes, the plugin fails to load on vesktop and shows a white screen.

**Comment by D3SOX** [comment]
Works fine with Vesktop for me

**Comment by verysillycat** [comment]
> Works fine with Vesktop for me

x2

**Comment by PinguLinux** [comment]
maybe im installing the plugin wrong, how does one install this plugin in vesktop?

**Comment by verysillycat** [comment]
> maybe im installing the plugin wrong, how does one install this plugin in vesktop?

[here are the instructions](https://www.youtube.com/watch?v=8wexjSo8fNw), i recommend removing the folder and then git cloning again or a full reinstallation of vesktop
* but instead of doing `pnpm install` like on 3:04 you need to go to `Settings --> Vesktop Settings --> Vesktop Location` and then select the git clone'd folder and then select the dir folder, and relaunch using the tray icon

![Vesktop_RNLhIY7Po1](https://github.com/Syncxv/vc-message-logger-enhanced/assets/126973723/59b462a3-57c7-4db8-931c-11192fbd78d4)

**Comment by PinguLinux** [comment]
Thanks, it worked!
